spring:
  application:
    name: challenge
    
server:
  port: 8080
management:
  port: 9001
  
logging:
  config: config/log4j2-console.xml

security:
  antMatchers: 
    -
      method: 'GET'
      url: '/info'
    -
      method: 'GET'
      url: '/hello'
    -
      method: 'POST'
      url: '/register'
    -
      method: 'POST'
      url: '/login'
      
jwt:
  secret: 'SecretKeyToGenJWTs'
  expirationTime: 1800000 # 1000 * 60 * 30 = 1800000 = 30 minutos
  tokenPrefix: ''
  headerString: 'Authorization'

---  
spring:
  profiles: debug
  # mysql  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/challenge
    username: root
    password: mysql
  # jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate.ddl-auto: create-drop
    database: MYSQL
logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG     

      
      
      